version: '3.7'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "1337:80"
    links:
      - server

  server:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8000:8080"